package eventids

const (
	EVENT_DOUBLE_TAP_1_FINGER = iota
	EVENT_DOUBLE_TAP_2_FINGERS

	EVENT_SWIPE_RIGHT_1_FINGER
	EVENT_SWIPE_DOWN_1_FINGER
	EVENT_SWIPE_LEFT_1_FINGER
	EVENT_SWIPE_UP_1_FINGER

	EVENT_SWIPE_RIGHT_2_FINGERS
	EVENT_SWIPE_DOWN_2_FINGERS
	EVENT_SWIPE_LEFT_2_FINGERS
	EVENT_SWIPE_UP_2_FINGERS

	EVENT_FB_SLEEP
	EVENT_FB_WAKE
)
